#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Language Version: 2.5.1
# Last Changed: 2009-12-30 14:49:33
"""docstring
"""

__author__ = "Maitreya Dutt Chao (leonardr@segfault.org)"
__version__ = "0.0.1"
__copyright__ = "Copyright (c) 2004-2008 Maitreya Dutt Chao"
__license__ = "New-style BSD"

import socket

def isconnected(addr):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(1)
    try:
        sock.connect(addr)
    except socket.error, e:
        #print e.args, 'xx:',e.message
        return 0
    sock.close()
    return 1

xx = {}
from address import addresses
for addr in addresses:
    xx.update({':'.join((addr[0],str(addr[1]))):isconnected(addr)})
#print '-', ''.join(str(xx).split())
print ''.join(str(xx).split())
#print isconnected(('localhost', 8000))
#print isconnected(('aix.unix-center.net', 8000))
#print isconnected(('192.168.0.111', 8000))
#print isconnected(('192.168.0.100', 2121))
#print sock.getsockopt(socket.SOL_IP,socket.IP_TTL)
def test():
    pass

if __name__ == '__main__':
    test()

