#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import sys
from string import strip, replace
data = []
for i in range(20):
    line = sys.stdin.readline()
    if not line: break
    data.append(line)

r = []
x = lambda s: replace(s, ' ', '&#10;') 
#for l in data.splitlines():
for l in data:
    r += map(strip, l.split('|'))

r = map(x, r)
print ' '.join(r)
#print r
#print len(r)
