#!/bin/sh
#echo '-'

sqlplus -S "/ as sysdba" << !
set heading off;
set feed off;
set line 850;
set pagesize 0;
set colsep "|"; 
column status format a6;
	column version format a10;
	column database_name format a13
	column instance_name format a13;
	column startup_time for a14;
	select a.instance_name,a.status,b.name database_name, a.database_status,a.version, b.created,b.log_mode,b.open_mode,a.startup_time
	from gv\$instance a
	, (select inst_id, name, created, log_mode,open_mode from gv\$database) b where a.inst_id=b.inst_id;
exit;
!
