#!/bin/sh

#echo '-'
sqlplus -S "/ as sysdba" << !
set heading off;
set feed off;
set line 450;
set pagesize 0;
set colsep "|";
    col tablespace_name for a20
        col file_name for a50
        col to_spa for 99999999999999

select tablespace_name,  file_name,
round(bytes/(1024*1024),0) total_space
from dba_data_files
order by tablespace_name;



exit;
!
