#!/bin/sh
#
#get_UDPv4_network_traffic
# 1.1.1.1 接口概念
# UDP层网络性能分析
#  1.1.1.2 输入
#  无
#   1.1.1.3 输出
#   采集时间、
#   indgram/s
#   otdgram/s
#   inerr/s
#   noport/s
#   socknow
#   sockmax
exists()
{
	type $1 2&>1 /dev/null
}
AIX(){ df -k|tail +2|sed 's/%//g';}
Digital(){ :;}
FreeBSD(){ :;}
HP_UX(){ :;}
Irix(){ :;}
Linux(){ sar -SU 1 1|tail -1;}
#Linux(){ dx -kP|tail -n+2|sed 's/%//g'; echo $?;}
OS390(){ :;}
SCO_SV(){ df -kP|tail -n+2|sed 's/%//g';}
SunOS(){ df -k|tail +2|sed 's/%//g';}
Tru64(){ :;}
UnixWare(){ df -kP|tail -n+2|sed 's/%//g';}
#Win32
default(){ df -k|tail +2|sed 's/%//g';}

INTERVAL=10	# Defines the total number of sampling intervals
HOST=`hostname`
OS=`uname`	# Defines the UNIX flavor
SECS=30		# Defines the number of seconds for each sample
STATCOUNT=0	# Initialize a loop counter to 0, zero

###################################################
##### SETUP THE ENVIRONMENT FOR EACH OS HERE ######
###################################################
$OS

# These "F-numbers" point to the correct field in the
# command output for each UNIX flavor.

       #echo " The Operating System is $OS "
##Linux
#exit
#case $OS in
#AIX)
#	$AIX
#       ;;
#HP-UX)
#	$HP_UX
#       ;;
#Linux)
#	echo $Linux
#	exec $Linux
#       ;;
#SCO_SV)
#	$SCO_SV
#       ;;
#SunOS)  
#	$SunOS
#       ;;
#UnixWare)
#	$UnixWare
#       ;;
#*)# echo " ERROR: $OS is not a supported operating system "
#	$default
#  # echo " ...EXITING... "
#   exit 1
#   ;;
#esac
#
####################################################
######### BEGIN GATHERING STATISTICS HERE ##########
####################################################
