#!/bin/sh
#
#get_CPU_Performance
# 1.1.1.1 接口概念
# 获得实时CPU占用率
#  1.1.1.2 输入
#  无
#   1.1.1.3 输出
#   采集时间、用户时间% 、系统时间%、wio,空闲时间%
#AIX(){ sar -u 1 1|awk 'NR==6{$1=$1" all";print$0}';}(需要root权限)
AIX(){ vmstat  1 2|tail -1|awk '{print "-  all "$14,$15+$17,$16}';}
Digital(){ :;}
FreeBSD(){ top -b  -s 1 -d 3 0|tail -7|sed 's/%//g'|awk '/CPU/{print $2,$4+$6+$8,0,$10}';}
HP_UX(){ :;}
Irix(){ :;}
#atsar:NF==9;sysstat:NF==7 or 8
Linux(){ sar -u 1 1|awk '$2~/all/{if(NF==9)print $2,$3,$4+$5+$6+$7+$8,$9;
                         if(NF==8)print $3,$4+$5+$7,$6,$8;
                         if(NF==7)print $2,$3,$4+$5+$6,$7}';}
OS390(){ :;}
SCO_SV(){ sar -u 1 1|awk 'NR==5{$1=$1" all";print $1,$2,$3,$4+$5,$6}';}
SunOS(){ sar -u 1 1|awk 'NR==5{$1=$1" all";print $1,$2,$3,$4+$5,$6}';}
Tru64(){ :;}
UnixWare(){ sar -u 1 1|awk 'NR==5{$1=$1" all";print $1,$2,$3,$4+$5,$6}';}
#Win32
default(){ df -k|tail +2|sed 's/%//g';}

INTERVAL=10	# Defines the total number of sampling intervals
#HOST=`hostname`
OS=`uname`	# Defines the UNIX flavor
SECS=30		# Defines the number of seconds for each sample
STATCOUNT=0	# Initialize a loop counter to 0, zero
#DATE=`date "+%Y-%m-%d %H:%M:%S"`


###################################################
##### SETUP THE ENVIRONMENT FOR EACH OS HERE ######
###################################################
$OS
#$OS|tr "\n" " "|sed "s/[0123456789:\-]* /${DATE} /"
#x=`$OS|tr "\n" " "`
#echo $x|sed "s/[0123456789:\-]* /${DATE} /"

# These "F-numbers" point to the correct field in the
# command output for each UNIX flavor.

       #echo " The Operating System is $OS "
##Linux
#exit
#case $OS in
#AIX)
#	$AIX
#       ;;
#HP-UX)
#	$HP_UX
#       ;;
#Linux)
#	echo $Linux
#	exec $Linux
#       ;;
#SCO_SV)
#	$SCO_SV
#       ;;
#SunOS)  
#	$SunOS
#       ;;
#UnixWare)
#	$UnixWare
#       ;;
#*)# echo " ERROR: $OS is not a supported operating system "
#	$default
#  # echo " ...EXITING... "
#   exit 1
#   ;;
#esac
#
####################################################
######### BEGIN GATHERING STATISTICS HERE ##########
####################################################
