#!/bin/sh
#
#get_swap_space
# 1.1.1.1 接口概念
# 取得交换分区的使用状态，在UNIX系统中，一般也把交换分区作为磁盘空间的一个特例，这种情况下，将交换分区的文件系统写为SWAP，挂载点写为SWAP。
#  1.1.1.2 输入
#  无
#   1.1.1.3 输出
#   采集时间、总大小、已用、可用
exists()
{
	type $1 2&>1 /dev/null
	retcode=$?
	return $retcode
}
AIX(){ lsps -s|awk 'NR==2{total=$1*1024;used=int($1*$2*10.24);free=total-used;print total,used,free}';}
Digital(){ :;}
FreeBSD(){ swapinfo -k|tail -n+2|awk 'BEGIN{free=0;used=0}{free+=$4;used+=$3}END{print free+used,used,free}';}
HP_UX(){ swapinfo -t|grep dev|awk '{print $2,$3,$4}';}
Irix(){ :;}
#Linux(){ free|awk '$1~/[Ss]wap/{print strftime("%T"),$2,$3,$4}';}
Linux(){ free|awk '$1~/[Ss]wap/{print $2,$3,$4}';}
OS390(){ :;}
SCO_SV(){ 
	swap -l|awk 'NR==2{print $5,$5-$4,$4}';
	#free=`swap -l|awk 'NR==2 {print $4}'`
        #  total=`swap -l|awk 'NR==2 {print $5}'`
        #  userd=`echo  "$total-$free"|bc`
        #  echo  '- '$total' '$userd' '$free;} #  需要root权限
}
#SunOS(){ swap -s|sed -e 's/k/ /g' -e 's/[^0-9| ]//g'|awk '{print "-",$3+$4,$3,$4}';}
SunOS(){ swap.py;}
Tru64(){ :;}
UnixWare(){ swap -l|awk 'NR==2{print "-",$5,$5-$4,$4}';}
#Win32
default(){ df -k|tail +2|sed 's/%//g';}

INTERVAL=10	# Defines the total number of sampling intervals
#HOST=`hostname`
OS=`uname`	# Defines the UNIX flavor
SECS=30		# Defines the number of seconds for each sample
STATCOUNT=0	# Initialize a loop counter to 0, zero
#DATE=`date "+%Y-%m-%d %H:%M:%S"`

###################################################
##### SETUP THE ENVIRONMENT FOR EACH OS HERE ######
###################################################
$OS
#$OS|tr "\n" " "|sed "s/[0123456789:\-]* /${DATE} /"

# These "F-numbers" point to the correct field in the
# command output for each UNIX flavor.

       #echo " The Operating System is $OS "
##Linux
#exit
#case $OS in
#AIX)
#	$AIX
#       ;;
#HP-UX)
#	$HP_UX
#       ;;
#Linux)
#	echo $Linux
#	exec $Linux
#       ;;
#SCO_SV)
#	$SCO_SV
#       ;;
#SunOS)  
#	$SunOS
#       ;;
#UnixWare)
#	$UnixWare
#       ;;
#*)# echo " ERROR: $OS is not a supported operating system "
#	$default
#  # echo " ...EXITING... "
#   exit 1
#   ;;
#esac
#
####################################################
######### BEGIN GATHERING STATISTICS HERE ##########
####################################################



## End of all-in-one_swapmon.ksh
