#!/bin/sh
#
# 1.1.1.1 接口名称
# get_disk_space_usage
#  1.1.1.2 接口概念
#  取磁盘空间占用率
#   1.1.1.3 输入
#   无
#    1.1.1.4 输出
#    采集时间、文件系统、大小（KB）、已用（KB）、可用（KB）、已用%、挂载点
exists()
{
	type $1 2&>1 /dev/null
}
#文件系统          1024块   Iused    可用 %Used    安装于
AIX(){ df -k|awk 'NR>1{print$1,$2,$5,$3,$4,$7}'|sed 's/%//g';}
Digital(){ :;}
FreeBSD(){ df -kP|tail -n+2|sed 's/%//g';}
HP_UX(){ :;}
#Irix(){ :;}
#文件系统         1024-块  已有  可用  容量 挂载点
Linux(){ df -kP|tail -n+2|sed 's/%//g';}
#OS390(){ ;}
SCO_SV(){ df -kP|tail -n+2|sed 's/%//g';}
SunOS(){ df -k|tail +2|sed 's/%//g';}
#Tru64(){ ;}
UnixWare(){ df -kP|tail -n+2|sed 's/%//g';}
#Win32
default(){ df -k|tail +2|sed 's/%//g';}

INTERVAL=10	# Defines the total number of sampling intervals
#HOST=`hostname`
OS=`uname`	# Defines the UNIX flavor
SECS=30		# Defines the number of seconds for each sample
STATCOUNT=0	# Initialize a loop counter to 0, zero
#DATE=`date "+%Y-%m-%d %H:%M:%S"`

###################################################
##### SETUP THE ENVIRONMENT FOR EACH OS HERE ######
###################################################
$OS
#$OS|tr "\n" " "|sed "s/[0123456789:\-]* /${DATE} /"
#x=`$OS|tr "\n" " "`
#echo $x|sed "s/[0123456789:\-]* /${DATE} /"

# These "F-numbers" point to the correct field in the
# command output for each UNIX flavor.

       #echo " The Operating System is $OS "
##Linux
#exit
#case $OS in
#AIX)
#	$AIX
#       ;;
#HP-UX)
#	$HP_UX
#       ;;
#Linux)
#	echo $Linux
#	exec $Linux
#       ;;
#SCO_SV)
#	$SCO_SV
#       ;;
#SunOS)  
#	$SunOS
#       ;;
#UnixWare)
#	$UnixWare
#       ;;
#*)# echo " ERROR: $OS is not a supported operating system "
#	$default
#  # echo " ...EXITING... "
#   exit 1
#   ;;
#esac
#
####################################################
######### BEGIN GATHERING STATISTICS HERE ##########
####################################################
